/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'elvis' at '8/13/17 4:54 PM' with Gradle 3.1
 *
 * @author elvis, @date 8/13/17 4:54 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
//  def getOSName(): String {
//
//  }
}
