/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'elvis' at '8/13/17 4:54 PM' with Gradle 3.1
 *
 * @author elvis, @date 8/13/17 4:54 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }

  test("osName get os") {
    def library = new Library()
    assert(library.os)
  }

}
